# Generated by Django 4.1.7 on 2023-03-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_inventory_medicine_order_status_vending_machines_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
