# Generated by Django 4.1.7 on 2023-03-23 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_medicine_medicine_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='medcine_id',
            new_name='medicine_id',
        ),
    ]
