# Generated by Django 4.1.7 on 2023-03-23 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_medicine_medicine_id_remove_orders_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vending_machines',
            name='machine_id',
        ),
    ]
