# Generated by Django 4.1.7 on 2023-04-08 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_profile_email_remove_profile_first_name_and_more'),
        ('polls', '0007_remove_vending_machines_machine_id'),
    ]

    operations = [
    ]
