# Generated by Django 4.1.7 on 2023-03-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_merge_20230323_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id_user',
            field=models.CharField(default=0, max_length=9, unique=True),
        ),
    ]
