# Generated by Django 4.1.7 on 2023-04-20 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_alter_inventory_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='medicine_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.medicine'),
        ),
    ]
