# Generated by Django 4.1.7 on 2023-04-20 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_orders_medicine_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='machine_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.vending_machines'),
        ),
    ]
