# Generated by Django 4.1.7 on 2023-04-20 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_orders_machine_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='machine_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.vending_machines'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='medicine_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.medicine'),
        ),
    ]
