# Generated by Django 4.1.7 on 2023-04-28 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_merge_20230408_2250'),
        ('polls', '0015_orders_qr_code'),
    ]

    operations = [
    ]
