# Generated by Django 4.1.7 on 2023-05-01 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_merge_0008_merge_20230408_2250_0015_orders_qr_code'),
        ('polls', '0017_alter_orders_qr_code'),
    ]

    operations = [
    ]
