# Generated by Django 4.1.7 on 2023-05-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_merge_20230501_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video_Channels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=90)),
            ],
        ),
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='prescription',
            field=models.CharField(max_length=100),
        ),
    ]
