# Generated by Django 4.1.7 on 2023-05-14 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0019_video_channels_alter_medicine_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_channels',
            name='pharmacist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video_channels',
            name='token',
            field=models.CharField(max_length=200),
        ),
    ]
