# Generated by Django 4.1.7 on 2023-05-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_pharmacist_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacist_call',
            name='anamnesis',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AlterField(
            model_name='pharmacist_call',
            name='instructions',
            field=models.CharField(default='None', max_length=500),
        ),
    ]
