# Generated by Django 4.1.7 on 2023-05-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_video_channels_pharmacist_alter_video_channels_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='is_prescription',
            field=models.BooleanField(default=False),
        ),
    ]
