# Generated by Django 4.1.7 on 2023-05-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_medicine_is_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_name',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='prescription',
            field=models.CharField(max_length=400),
        ),
    ]
